# Generated by Django 2.1.7 on 2019-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('warehouse_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=14)),
            ],
        ),
    ]
