# Generated by Django 2.1.7 on 2019-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgmt', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
