# Generated by Django 2.1.7 on 2019-04-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgmt', '0004_auto_20190401_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
