# Generated by Django 2.1.7 on 2019-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgmt', '0006_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(max_length=20),
        ),
    ]
