# Generated by Django 2.1.7 on 2019-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgmt', '0007_auto_20190403_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=20)),
                ('p_image', models.ImageField(upload_to='')),
                ('p_uploader', models.CharField(max_length=20)),
            ],
        ),
    ]
